todo/urls.py
from django.urls import path
from . import views


app_name = "todo"

urlpatterns = [
    path("", views.signup, name="index"),
    path("login/", views.user_login, name="login"),
    path("todopage/", views.todo_pg, name= 'todopage'),
    path("signout/", views.signout, name='signout'),
    path("edit_todo/<int:srno>", views.edit_todo, name= 'edit_todo'),
    path("delete_todo/<int:srno>", views.delete_todo, name='delete_todo')
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_to_todo(request):
    return redirect('todo/')


urlpatterns = [
    path('', redirect_to_todo, name="root"),
    path("todo/", include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class TODOO(models.Model):
    srno = models.AutoField(primary_key=True, auto_created=True)
    title = models.CharField(max_length=25)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from todo.models import TODOO
from django.contrib.auth import authenticate, login, logout
from todo import models
from django.contrib.auth.decorators import login_required

# Create your views here.




def signup(request):
    # return HttpResponse("Hello, world. You'r at the todo index.")

    if request.method == 'POST':
        fnm = request.POST.get('fnm')
        emailid = request.POST.get('emailid')
        pwd = request.POST.get('pwd')
        print(fnm, emailid, pwd)
        my_user = User.objects.create_user(fnm, emailid, pwd)
        my_user.save()
        return redirect('/todo/login')
    return render(request, "signup.html")


def user_login(request):
    if request.method == 'POST':
        fnm = request.POST.get('fnm')
        pwd = request.POST.get('pwd')
        print(fnm, pwd)
        userr = authenticate(request, username=fnm, password=pwd)
        if userr is not None:
            login(request, userr)
            return redirect('/todo/todopage')
        else:
            return redirect('/todo/login')
        
    return render(request, "login.html")


@login_required(login_url='/todo/login')
def todo_pg(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        print(title)
        obj = models.TODOO(title= title, user= request.user)
        obj.save()
        res = models.TODOO.objects.filter(user= request.user).order_by('-date')
        return redirect('/todo/todopage', {'res': res})
    
    res = models.TODOO.objects.filter(user= request.user).order_by('-date')
    return render(request, 'todos.html', {"res":res})


def signout(request):
    logout(request)
    return redirect('/todo/login')




@login_required(login_url='/todo/login')
def edit_todo(request, srno):
    if request.method == 'POST':
        title = request.POST.get('title')
        print(title)
        obj = models.TODOO.objects.get(srno=srno)
        obj.title = title
        obj.save()
        return redirect('/todo/todopage')

    obj = models.TODOO.objects.get(srno=srno)
    return render(request, 'edit_todo.html', {'obj': obj})


@login_required(login_url='/todo/login')
def delete_todo(request, srno):
    obj = models.TODOO.objects.get(srno=srno)
    obj.delete()
    return redirect('/todo/todopage')

todo/templates/edit_todo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Font Awesome 5 Brands:wght@400&display=swap" />
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>

</head>

<body>
    
    <div class="signup-login">
        <div class=" signup-box scr">
            <div class="heading">Get Things Done?</div>
            <form method="post">
                {% csrf_token %}
                <input type="text" name="title" required class="todo-input inp" placeholder="What is the task today?" value={{obj.title}}>
                <input type="hidden" name="srno" value={{obj.srno}}>
                
                <input class="submit-button" type="submit" value="Update Task">

            </form>

            {% for todo in res %}
            <div class="Todo clickable-div {% if todo.status %}todo-green{% else %}todo-red{% endif %}" >
                <h5>{{todo.srno}}</h5>
                <p>{{todo.title}}</p>
            



                <div>
                    <!-- <a href=""><i class="fa-solid fa-pen-to-square"></i></a> -->
                    <a href="{% url 'todo:edit_todo' todo.srno %}"><i class="fa-solid fa-pen-to-square"></i></a>

                    <a href=" /delete_todo/{{todo.srno}} "><i class="fa-solid fa-trash"></i></a>

                    </i>
                </div>
            </div>


            {% endfor %}
        </div>


    </div>
    <script src="{% static 'js/todo.js' %}"></script>
</body>

</html>

todo/templates/login.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, width=device-width" />
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Font Awesome 5 Brands:wght@400&display=swap" />
  <title>Login</title>
</head>

<body>
  <div class="signup-login">
    <div class="signup-box1">

      <form method="post">
        {% csrf_token %}
        <div class="heading">
          Login
        </div>
        <div class="line"></div>
        

        <div class="field">
          <b>Username</b>

          <input class="inp" type="text" name="fnm" required placeholder="Enter Your Username">
        </div>

        <div class="field">
          <b>Password</b>

          <input class="inp" type="password" name="pwd" required placeholder="Enter Password">
        </div>

        <div class="field">
          <input class="submit-button" type="submit" value="Login">
        </div>
        <div class="line"></div>
        <div class="field">
          <b style="margin-left:130px;">Don't have an account? </b>
          <br>
          <a class="anc" href="/">Signup</a>
        </div>

      </form>
    </div>



  </div>
</body>

</html>

todo/templates/signup.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Font Awesome 5 Brands:wght@400&display=swap" />
</head>

<body>
    <div class="signup-login">
        <div class="signup-box">
            <form method="post">
                {% csrf_token %}
                <div class="heading">
                    SignUp
                </div>

                <div class="line"></div>
                <div class="field">
                    <b>Username</b>

                    <input class="inp" type="text" name="fnm" required placeholder="Enter Your Full Name">
                </div>


                <div class="field">
                    <b>Email</b>

                    <input class="inp" type="email" name="emailid" required placeholder="Enter Your Username">
                </div>


                <div class="field">
                    <b>Password</b>

                    <input  class="inp" type="password" name="pwd" required placeholder="Enter Password">
                </div>
                <div class="field">
                    <input class="submit-button"type="submit" value="Signup">
                </div>
                <div class="line"></div>

                <div class="field">
                    <b style="margin-left:130px;">Already have an account?</b>
                    <br>
                    <a class="anc"href="login">Login</a>
                </div>





            </form>

        </div>

    </div>
</body>

</html>

todo/templates/todos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Font Awesome 5 Brands:wght@400&display=swap" />
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>

</head>

<body>
    <div class="signup-login">
        <div>
            <div>
                <h1>Hello {{user}}</h1>
            </div>
            <div class=" signup-box scr">
                <div class="heads">
                    <div class="ancaa" title=""><i class="fa-solid fa-user"></i> </div>
                    <div class="heading">Get Things Done? </div>
                        <div class="anca"><a href="{% url 'todo:signout' %}" class="sign" title="signout"><i
                                class="fa-solid fa-right-from-bracket"></i></a></div>
                </div>


                <form method="post">
                    {% csrf_token %}
                    <input type="text" name="title" required class="todo-input inp"
                        placeholder="What is the task today?">


                    <input class="submit-button" type="submit" value="Add Task">

                </form>

                {% for todo in res %}
                <div class="Todo clickable-div {% if todo.status %}todo-green{% else %}todo-red{% endif %}">
                    <form method="post" action="">
                        {% csrf_token %}

                        <!-- <h5><input name="status"required type="submit" {% if todo.status %} checked {% endif %}></h5> -->
                    </form>

                    <p class="{% if todo.status %} completed {% endif %} ">{{todo.title}}</p>




                    <div>
                        <!-- <a href=" edit_todo/{{todo.srno}} "><i class="fa-solid fa-pen-to-square"></i></a> -->
                        <!-- <a href=" delete_todo/{{todo.srno}} "><i class="fa-solid fa-trash"></i></a> -->

                        <a href="{% url 'todo:edit_todo' todo.srno %}"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a href="{% url 'todo:delete_todo' todo.srno %}"><i class="fa-solid fa-trash"></i></a>

                        </i>
                    </div>
                </div>


                {% endfor %}
            </div>


        </div>
    </div>
    <script src="{% static 'js/todo.js' %}"></script>
</body>

</html>